### ISSUE TITLE
New Tool Window for TODO list

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#19]
Also: customizable dictionary of keywords and color mappings (that will also appear in the tool window)

**Comment by pramod-hegde** [comment]
need to cleanup UI.

**Comment by justcla** [comment]
It turns out this is already included in Visual Studio.
It's called "Task List" and available on the View menu. (Ctrl-W, T)
And you can add extra "tokens" in the tools options Environment->Task List.
You can't specify colors, but you can specify priorities.

**Comment by justcla** [comment]
Closing this issue since it is already implemented in Visual Studio.

**Comment by aakash-1906** [comment]
Hi Justin. Can't we try to enhance the existing Task List of Visual Studio with colors. May be as a low priority but an essential task, later?
