### ISSUE TITLE
Add command: Go to document on the left/right

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#2]
Suggested key bindings: Alt+Left / Alt+Right

**Comment by justcla** [comment]
<Shortcut Command="Window.NextTab" Scope="Global">Alt+Right Arrow</Shortcut>
<Shortcut Command="Window.PreviousTab" Scope="Global">Alt+Left Arrow</Shortcut>
<Shortcut Command="Window.NextTab" Scope="Text Editor">Alt+Right Arrow</Shortcut>
<Shortcut Command="Window.PreviousTab" Scope="Text Editor">Alt+Left Arrow</Shortcut>
<Shortcut Command="Window.NextTab" Scope="Workflow Designer">Alt+Right Arrow</Shortcut>
<Shortcut Command="Window.PreviousTab" Scope="Workflow Designer">Alt+Left Arrow</Shortcut>

**Comment by carsonal** [comment]
Wont fix because problem does not exit. Just need to overwrite the mapping.
