### ISSUE TITLE
Add command: Go to most recent edit location

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#5]
Suggested key binding: Ctrl+Shift+Backspace

**Comment by lorenpaulsen** [comment]
How is this different than Ctrl+Minus?

**Comment by justcla** [comment]
Ctrl+Minus goes to the last place navigated. If you have navigated to 10 different places since making a code change (which is not uncommon when following a code discovery path), then Ctrl+Shift+Backspace will go immediately to the last edit, and save you numerous actions of Ctrl+Minus.

**Comment by justcla** [comment]
This command is now available in v2.1.2

**Comment by justcla** [comment]
Added in PR #75
