### ISSUE TITLE
Attempting to Install to VS 2017 Results in NullReferenceException

### ISSUE THREAD

**Issue by yannduran** [justcla/HotCommands#54]
Here's the log entry that was generated:

19/12/2016 7:04:29 PM - Microsoft VSIX Installer
19/12/2016 7:04:29 PM - -------------------------------------------
19/12/2016 7:04:29 PM - vsixinstaller.exe version:
19/12/2016 7:04:29 PM - 15.0.26014.0 built by: D15REL
19/12/2016 7:04:29 PM - -------------------------------------------
19/12/2016 7:04:29 PM - Command line parameters:
19/12/2016 7:04:29 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26014.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\Yann\AppData\Local\Temp\VSIXvrc0roc3.vsix
19/12/2016 7:04:29 PM - -------------------------------------------
19/12/2016 7:04:29 PM - Microsoft VSIX Installer
19/12/2016 7:04:29 PM - -------------------------------------------
19/12/2016 7:04:29 PM - Initializing Install...
19/12/2016 7:04:29 PM - Extension Details...
19/12/2016 7:04:29 PM - 	Identifier         : e8175b11-0e09-42b5-9c3c-ba7bfb53a311
19/12/2016 7:04:29 PM - 	Name               : Hot Commands for Visual Studio
19/12/2016 7:04:29 PM - 	Author             : Justin Clareburt
19/12/2016 7:04:29 PM - 	Version            : 1.1.3
19/12/2016 7:04:29 PM - 	Description        : A collection of commands, analyzers, and refactorings for enhanced productivity in Visual Studio IDE
19/12/2016 7:04:29 PM - 	Locale             : en-US
19/12/2016 7:04:29 PM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotCommandsforVisualStudio
19/12/2016 7:04:29 PM - 	InstalledByMSI     : False
19/12/2016 7:04:29 PM - 	SupportedFrameworkVersionRange : [4.5,)
19/12/2016 7:04:29 PM - 
19/12/2016 7:04:29 PM - 	SignatureState     : Unsigned
19/12/2016 7:04:29 PM - 	Supported Products : 
19/12/2016 7:04:29 PM - 		Microsoft.VisualStudio.Community
19/12/2016 7:04:29 PM - 			Version : [14.0,16.0)
19/12/2016 7:04:29 PM - 
19/12/2016 7:04:29 PM - 	References         : 
19/12/2016 7:04:29 PM - 	Prerequisites      : 
19/12/2016 7:04:29 PM - 		-------------------------------------------------------
19/12/2016 7:04:29 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
19/12/2016 7:04:29 PM - 		Name         : Visual Studio core editor
19/12/2016 7:04:29 PM - 		Version      : [15.0.25826.2,16.0)
19/12/2016 7:04:29 PM - 
19/12/2016 7:04:29 PM - Signature Details...
19/12/2016 7:04:29 PM - 	Extension is not signed.
19/12/2016 7:04:29 PM - 
19/12/2016 7:04:31 PM - The extension with ID 'e8175b11-0e09-42b5-9c3c-ba7bfb53a311' is not installed to Microsoft Visual Studio Enterprise 2017 RC.
19/12/2016 7:04:31 PM - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.LocationBasedSKU.IntializePackages()
   at VSIXInstaller.LocationBasedSKU.GetSetupDependencies(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at VSIXInstaller.LocationBasedSKU.GetSetupDependencies(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by yannduran** [comment]
Hmm, interesting. If I download the vsix and install it locally, it doesn't even suggest VS 2017.

Before I upgraded HC in VS 2015, I got this:

![image](https://cloud.githubusercontent.com/assets/2031126/21305356/4fdfe374-c61f-11e6-8377-caf660da1ace.png)

After I upgraded in VS 2015, I got this:

![image](https://cloud.githubusercontent.com/assets/2031126/21305465/085d28b2-c620-11e6-9df1-8c83833fe291.png)

I'm actually having a very similar problem myself actually now that I think of it. This may be way more widespread than just Hot Commands.

Maybe the null reference is from there being no instances to install to and the lack of any instances isn't being handled in the VSIX installer. Though why it's not applying to VS 2017 I can't figure out. My extension was "upgraded" by VS 2017, I added the editor core as a prerequisite.

I see some documentation talking (very vaguely) about checking the compiled VSIX for manifest.json and catalog.json. My extension doesn't have either, though HC does have both files.

In Preview 5, having the GenerateVsix3 attribute in the manifest was supposed to generate the json files. But now I don't know what's supposed to generate them, or if I need to manually add them. It's very frustrating!

**Comment by justcla** [comment]
Lots of issues to discuss here.

For a start, we no longer need "GenerateVsixV3" anywhere. That was only for Preview 5.

This version of HC was generated by VS2015 using the new SDK.14.0 Build tools.
It installed on my machine, but I had to restart VS2017 to get it to show up, and even then it was disabled and I had to enable and restart. I've been having that issue with other extensions, so not sure what's going on there.

Yes, a VSIXv3 should have the two json files - and "prerequisites" in the manifest. Otherwise it will not be recognised as VSIXv3.

If you are trying to "upgrade" from outside VS, you will need to uninstall the original one, or it will show it as already installed.

As for the NullReference, maybe that's because I built it with VS2015 instead of VS2017. I'll check it out.

Cheers

P.S. Did you notice I added Join Lines? ;-) It could be better, but at we've got something there.

**Comment by justcla** [comment]
Maybe your system did not suggest installing to VS2017RC because you have a version already installed. (?)

**Comment by justcla** [comment]
This could also be an issue with prerequisites.
I've only declared CoreEditor as prerequisites. But maybe it needs more than that in order to run.

Or it could just be a bug with the installer.

What version are you running?

**Comment by yannduran** [comment]
If it needs more than just core it should be asking to install any other prerequisites, so that would also be a bug (unless fixed in RC refresh - who the hell names these things??!! what's wrong with RC2 or RC2.5).

I'm running RC, I haven't been able to find a way to actually get the "RC refresh" to install!

**Comment by yannduran** [comment]
Btw, V1.1.4 still gives me the null reference exception :(

**Comment by justcla** [comment]
I need to specify the prerequisites in the extension manifest. But I have only specified CoreEditor. If it needs a version of .Net or some of the VSSDK I will need to work that out, then add that to the prerequisites - so that it can prompt you to install the components that you're missing.

...but I haven't worked out what the minimum requirements are yet.

Regardless, I think that missing components only surface as an exception when you go to run the extension. But I might be wrong. Maybe it's unable to install without the correct prerequisites.
FYI I run with two workloads: .Net Desktop and Extensibility.

**Comment by yannduran** [comment]
It's a bit of a mess atm. 

I can't even install the extensibility tools (which I thought weere supposed to be installed when you select the extensibility workload. The extension gets queued to be installed (I still hate this btw), but when I close the VS 2017 instance (with no other instances running) the vsix installer never gets called.
