### ISSUE TITLE
InitializeFieldFromConstructor causes exception

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#63]
User [Maarten Boelens](https://developercommunity.visualstudio.com/users/834/87d49a88-0de7-4653-9614-7eddbdc18903.html) reported [error on Developer Community](https://developercommunity.visualstudio.com/content/problem/52915/initializefieldfromconstructor-exception.html).

> I keep getting a InitializeFieldFromConstructor exception (yellow bar on top of the editor) just by clicking on a private field. Here's the stack trace:
> System.NullReferenceException : Object reference not set to an instance of an object. at HotCommands.InitializeFieldFromConstructor.<>c_DisplayClass1_0.<GetConstructors>b_0(ConstructorDeclarationSyntax x) at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source) at async HotCommands.InitializeFieldFromConstructor.ComputeRefactoringsAsync(<Unknown Parameters>) at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

**Comment by lorenpaulsen** [comment]
Proposed fix here #67

**Comment by justcla** [comment]
Fixed.
