### ISSUE TITLE
Make Change Modifier work on methods

### ISSUE THREAD

**Issue by tiesmaster** [justcla/HotCommands#66]
As discussed in #64, methods should also provide the "Change Modifier" refactoring. I'll see if I can make it work.

**Comment by tiesmaster** [comment]
@justcla I need some advice on how to do this.

I was taking a stab at this, but it's actually quite difficult, since there is no base class with `Modifiers` on it: for types you need `BaseTypeDeclarationSyntax`, for methods you need `BaseMethodDeclarationSyntax`, although both derive from `MemberDeclarationSyntax`, it doesn't contain `Modifiers`, since it represents a number of declarations, where some of them don't have modifiers, like namespace declarations.

I'm considering introducing a "wrapper" class which would represent either types, or methods (or maybe also properties, and fields, since I think it would add value to have this refactoring for these as well). I have some work in progress (see this [branch](https://github.com/tiesmaster/HotCommands/commit/3613bb8291b383d5770556b33ce2352026fc28ae)), but I'm not sure if this is the right approach. What do think about solving it like this?

---

BTW I also though about doing this with generics somehow, but don't think they are of any help here. I find it quite odd that there is no base class for working with modifiers, am I maybe overlooking something?

**Comment by tiesmaster** [comment]
@justcla ^^^^^

In the mean time, I've come across [this blogpost](https://blog.decayingcode.com/post/contributing-to-open-source-my-first-roslyn-pull-request-fixing-the-bug/), where in the process of making a first PR to Roslyn, they eventually realizes that some code can be replaced with the `SyntaxGenerator`.

It looks like we can use that too here, by making use of `generator.WithAccessibility()` to set the accessibility. That might make it a lot simpler. Are you open to that?

**Comment by justcla** [comment]
Yes, I'm totally open to that.

**Comment by tiesmaster** [comment]
Ok, cool. I have the refactoring working with the generator, check out [this branch](https://github.com/tiesmaster/HotCommands/commit/598201ea38fadf87e571faf533f61b853aab2514). Though, I'm running into a couple issues, so I need some feedback.

The `SyntaxGenerator` gives you an abstraction, and with that you always loose some control, and that's also the case here. As a result of that, I'm unable to reproduce the exact same behavior, but slightly modified, this is because the generator will always generate the new modifier list in a [predefined order](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpSyntaxGenerator.cs,1688). These are the issues:

 * you get `internal protected`, instead of `protected internal`
 * accessibility modifiers always come first, then the others, so [`static public` to private will result in `private static`...](https://github.com/tiesmaster/HotCommands/commit/598201ea38fadf87e571faf533f61b853aab2514#diff-fe576132d18670104046a1c9ad1ff69fR59)

Before I refactor the "analysis" part, I first want to know what you think about this. I don't mind about that, since that's idiomatic C# anyhow, but you might want to keep it as it is.

---

Further, as you can see in the work-in-progress branch, I've added unit tests, because it makes it way easier to investigate things. Do you have any objections in adding them? Might be useful to put them in a separate PR, if you have some feedback on the choices I did there (like naming, using xUnit, etc.).

Let me know what you think about it.

**Comment by justcla** [comment]
Thanks for adding unit tests. That's a great idea. :-)

Oh, that's a bit annoying. Why does it order the modifiers that way?
Does C# have a standard?
Better to have something than nothing. But it would be better still if things could be ordered in the normal C# standard way.

**Comment by tiesmaster** [comment]
Frankly, I don't know. I don't think there is a "C# standard" for something like this, but this might be covered by something like the .NET Framework design guidelines, or something like what's considered ["Visual Studio defaults"](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md#c-coding-style), but yeah, I'm really not sure.

But what surprises me, is that this syntax generator thing actually looses the "full fidelity" of the syntax tree, one of the key characteristics of Roslyn. I'll explain what I mean with that. Your question triggered the hypothesis that code comments between modifiers are lost when you use the generator. I've just tested this in the following [unit test](https://github.com/tiesmaster/HotCommands/commit/eb98541276770726764ccdaf6bdda6f920d2290a), and that actually fails, which is very bad imho. A refactoring like this shouldn't blow something like that away, even though it's not the end of the world, I do think this is the whole premise of using Roslyn for things like these, and the syntax generator should honour that. I'll create an issue for that on the Roslyn repo, to see what the team has to say about that.

Having that said, I do think we can salvage this by incorporating the ideas of the syntax generator. So my proposal is to copy the [{Get,Set}ModifierTokens](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpSyntaxGenerator.cs,1580) method from Roslyn, and then we can make use of the same approach, and do the low level token list manipulation by hand. That should do the trick.

First, I'll create a PR for the unit tests, then I'll try to apply the approach above.

**Comment by justcla** [comment]
I really appreciate you doing that. Thanks.
I completely agree with what you've said. Keeping comments, etc is important. We can't just blow them away. If the tool isn't handling all method signature "trivia", then it's not very useful. Please do raise an issue for Roslyn on this.

I don't fully understand your suggested approach, but it sounds like you've got a plan. If it works, I'll accept it. :-)

Thanks for the effort you're putting into this.
And thanks for helping test the SyntaxGenerator and reporting issues on it.

**Comment by tiesmaster** [comment]
Just a quick update on this issue. I was working on this until a couple weeks ago, but I've been swamped the last couple of weeks, so no progress anymore, and I'm away on holiday the next 3 weeks, so don't expect any PRs soon. When I get back, I expect to have some time to finish [this branch](https://github.com/tiesmaster/HotCommands/tree/change-modifier/refactor)

**Comment by tiesmaster** [comment]
Stale
