### ISSUE TITLE
HotCommand uses legacy API in VS 2019

### ISSUE THREAD

**Issue by tiesmaster** [justcla/HotCommands#81]
First, HotCommands is awesome ❤️

I don't know if you noticed (see screenshot below), but VS 2019 now marks any extensions still using the "sync" `Package` base class get marked as using a deprecated API, and are advised to upgrade to the _new-ish_ `AsyncPackage` API. The "Learn More" points to [this page](https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019).

![image](https://user-images.githubusercontent.com/460904/55584152-de815300-5723-11e9-8cf0-ae75c7b6cd9f.png)

**Comment by DaniloNovakovic** [comment]
@justcla Visual Studio 2019 now blocks extensions by default that use "sync", so this extension is so far unusable in 2019.  #82 Should fix this problem.

**Comment by justcla** [comment]
Thanks!

**Comment by tiesmaster** [comment]
@justcla Any idea when you have the time to look at this? Right now, I've been dismissing the notification every time VS starts up, and warns about legacy extensions. However, I'd be nice if this extension would get updated, so startup of VS is also not affected.

BTW I tried to build PR #82 locally, but I'm getting build errors (probably due to missing workloads). So I also cannot run the fixed version myself locally :(

**Comment by justcla** [comment]
Actually, I tried earlier today.
I had build errors - failing to fetch packages from NuGet. I'll try again tomorrow.

**Comment by justcla** [comment]
Fyi. I see there's now a setting to allow AutoLoad extensions.

**Comment by tiesmaster** [comment]
This one, right? Already enabled 😉 

BTW I also got build errors on the PR, but now tried `master` and that also has build errors, so I'm guessing something broke in 2019. I'll see if you can find anything out.

![image](https://user-images.githubusercontent.com/460904/58943915-0a9b6d80-8781-11e9-8e5b-be74e5f3f3b5.png)

**Comment by tiesmaster** [comment]
@justcla I've looked at the build errors briefly, but couldn't really figure it out. I see that the `Microsoft.VisualStudio.*` assemblies are all added to the project through NuGet, but MSBuild all takes them not from the hint path, but from the VSSDK installed along side with VS. This is not really an area I'd like to go right now 😨

**Comment by justcla** [comment]
Updated to run Async now
