### ISSUE TITLE
Any chance for a VS2022 version? I'm missing move member up/down so much...

### ISSUE THREAD

**Issue by kowgli** [justcla/HotCommands#86]
If not what is the license of the source code? Is it OK to take snippets of it and try to create a VS2022 move member plugin?

**Comment by justcla** [comment]
The source code is open source. You're welcome to give it a go.

I'll try to release a 2022 version this year.

**Comment by justcla** [comment]
Done. The extension has now been upgraded for VS2022.

A new version for VS2017 and VS2019 exists in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotCommands2017) and in the releases. ([v3.1.0](https://github.com/justcla/HotCommands/releases/tag/v3.1.0))
