### ISSUE TITLE
Add command: DuplicateLinesUp (a.k.a. CopyLinesUp)

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#93]
Question asked on Visual Studio Marketplace: By Carl Foghammar Nömtak 9/02/2023

> It would be nice with an Edit.DuplicateLines that copies upward, in addition to the current one. So we can replicate functionality of vs code shift + alt + up/down.

**Comment by justcla** [comment]
Ok, I'll see if I can add the "Copy Lines Up" command.

**Comment by justcla** [comment]
Implemented in release v4.2.0

**Comment by justcla** [comment]
Known bug: There exists strange behaviour when the selection ends on the start or end of a line - in multi-caret mode. Work-around exists for single-selection mode (adjusts end of selection after new lines added increase the selection).

User Carl Foghammar Nömtak reports additional error:
>From my testing it works as expected as long as neither the start or end positions of the selection is at a line start or ending (even with multi caret). If they are, many bugs occur.

**Comment by justcla** [comment]
Indeed, when VS adds text to the end of a selection, it extends the selection (Basically a VS feature/bug).
I tried various ways to work around it, but any time the selection ends on a line, or starts on the next line, adding text to that point extend the original selection.

When there is only one selection, it's easy enough to use editorOperations to select the original text, or move the caret. But if there are multiple carets, any editorOperation on the selection or caret seems to break the multi-carets. :-( Sad panda.

I have dreamed of solutions where I adjust the end of the selection back two points, then move it forward again after adding the text. And this would be fine, but not really different to adjusting the caret or selection after the event - both basically affect a single caret, and break existing multi-caret. stuff.

So...the ultimate solution might be to store and reset every selection (including zero-length selections) after operating on them.
And...I did try implementing this, but I haven't been able to find a way to restore more than one selection.
So this is where we are. If I can get help with restoring multiple selections, I can brute force reset all selections.

**Comment by cfognom** [comment]
I'd love to help, but I have problems with building the package. Most of the project's references are yellow (can't be found). However, running "Restore NuGet Packages" on the solution tells me: "All packages are already installed and there is nothing to restore." Not sure what I'm doing wrong, its probably a newbie mistake, but I can't figure it out. Any idea what I might be doing wrong?

**Comment by cfognom** [comment]
It seems like the project expects the packages to be in "..\packages" but this folder is missing for me. I think I have all packages installed in the user directory ".nuget\packages". Is there some command to copy the required packages from ".nuget\packages" to "..\packages" that I'm not aware of?

**Comment by justcla** [comment]
It's not a rookie mistake. It's an absolute pain. The project has evolved over many many years and the way packages are referenced has also changed. So now it's a complete mess. I'm surprise I can build the thing myself. The whole thing should be cleaned up and simplified. Most of those references aren't needed. And they should probably be all fetched through NuGet. So don't feel out of place. What you are experiencing is very common. If you could delete all the references and then add them back with NuGet - one by one, that would be a great step moving forward. I would take that pull request separately (and welcome it).

**Comment by justcla** [comment]
This issue was fixed by @cfognom . Released on version 4.3.0

Thanks Carl
