### ISSUE TITLE
Re-write DuplicateSelection

### ISSUE THREAD

**Issue by justcla** [justcla/HotCommands#95]
The code for DuplicateSelection uses EditorOperations and doesn't work well with multiple cursors.
It's also not really clean and has much duplication.
This code should be written much more like DuplicateLines, carefully avoiding moving the caret unless necessary.

Hey Carl, @cfognom , Can you please take a look while your knowledge is fresh?

**Comment by cfognom** [comment]
I could probably do it. But duplicate selection is already in the default Visual studio, so what's the point of having a command that does exactly the same thing? Legacy reasons?

Sure, there is no reversed variant. Is that the main reason to include the command?

**Comment by cfognom** [comment]
Anyways, it was quite easy to implement, I could reuse most logic of duplicate lines. Pull request is open.

I basically just added a conditional that determines whether the duplication span should be the selected span or the selected-lines span, and use same code for both commands.

**Comment by justcla** [comment]
> But duplicate selection is already in the default Visual studio, so what's the point of having a command that does exactly the same thing?

Just for clean code. :-) As you say, it's kind of pointless unless we back-port it to the older versions of the plugin (which we should do!) But hey, who knows what the next request will be? So it would be nice to not be maintaining hundreds of lines of redundant and duplicated code. That was my thinking.

**Comment by justcla** [comment]
And wow, didn't you do an amazing job! As I knew you would. :-D
What a beautiful solution.
I especially love this part:

`bool isDuplicateLinesForThisSelection = isDuplicateLines || selectionSpan.Length == 0;`

That is such a nice clean way to capture this rule across both commands (DuplicateSelection and DuplicateLines). 👏

I'll test, build and release the updated extension with your new PR.
Thanks so much for doing this!

**Comment by justcla** [comment]
Release in v4.3.1
